project:
  type: website

website:
  title: "Jordan Herbert - Hydrologist"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Presentations and Publications"
        href: pubs.qmd
      - text: "Blog"
        href: blog.qmd
      - text: "CV"
        href: herbert_cv.pdf


format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

callout-appearance: simple







