---
title: "Presentations and Publications"
---

# Publications

Herbert, J. N., Raleigh, M. S., & Small, E. E. (2025). [*Using a Random Forest Model to Combine Airborne Lidar
and Snotel Data for Daily Estimates of Snow Depth Across Mountain Drainage Basins of Colorado*].  (https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2024WR039775). Water Resources Research. 

Herbert, J. N., Bromley, G. R. M., Kelly, M. A., Doughty, A. M., and others (2025). [*Paleoclimatic implications of glacial fluctuations in the Sierra Nevada del Cocuy, northern Andes, Colombia, during the Lateglacial and Holocene*](https://www.sciencedirect.com/science/article/pii/S0277379125002781). Quaternary Science Reviews.

Herbert, J. N., Raleigh, M. S., & Small, E. E. (2024). [*Reanalyzing the spatial representativeness of snow depth at automated monitoring stations using airborne lidar data*](https://tc.copernicus.org/articles/18/3495/2024/). The Cryosphere. 

# Presentations
Herbert, J. N., Raleigh, M. S., & Small, E. E. (2024). *A spatiotemporally expanded snow validation dataset: Integrating snow station and lidar data through machine learning*. American Geophysical Union Annual Meeting (poster). 

Herbert, J. N., Raleigh, M. S., & Small, E. E. (2024). *Integrating snow station and lidar data with machine learning: A daily, spatially representative snow validation dataset*. Nasa Snow Community Meeting (poster). 

Herbert, J. N., Raleigh, M. S., & Small, E. E. (2023). *Apples to apples, and apples to oranges: assessing snow pillow representativeness with airborne Lidar*. American Geophysical Union Annual Meeting (talk). 

Herbert, J., Kelly, M., Bromley, G., Doughty, A., Ruiz-Carrascal, D., Hidy, A., & Restrepo-Moreno, S. (2021). *Climate change in the northern tropical Andes during Termination 1 derived from glacier reconstructions: The Sierra Nevada del Cocuy Case*. Geological Society of America Annual Meeting (talk).  

Herbert, J. N., Gillikin, D., Molloy, J. B., Lama Sherpa, T., & Rodbell, D. T. (2018). Investigating the causes of eutrophication in high Andean lakes (Junín region, Peru) through nitrogen isotope analysis of sediment cores. Geological Society of America Annual Meeting (poster). 



